name: Publish Python Package to GitHub Packages

on:
  push:
    tags:
      - 'v*'  # Triggers on tag like v0.1.0
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Publish to GitHub Packages
      run: |
        pip install twine
        twine upload --repository-url https://crostonj.pkg.github.com/ dist/*
      env:
        TWINE_USERNAME: crostonj
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}